DEBUG 2015-08-05 17:28:12,097: 	 Executing command: 'submit'
DEBUG 2015-08-05 17:28:12,098: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 17:28:12,109: 	 Checking credentials
DEBUG 2015-08-05 17:28:12,109: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 17:28:12,109: 	 Getting proxy life time left
ERROR 2015-08-05 17:28:12,174: 	 Keyboard Interrupted
DEBUG 2015-08-05 17:28:14,630: 	 Executing command: 'submit'
DEBUG 2015-08-05 17:28:14,630: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 17:28:14,639: 	 Checking credentials
DEBUG 2015-08-05 17:28:14,640: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 17:28:14,640: 	 Getting proxy life time left
DEBUG 2015-08-05 17:28:15,348: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -timeleft
 output : 84856

 error: 
 retcode : 0
DEBUG 2015-08-05 17:28:16,093: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -actimeleft
 output : 84856

 error: 
 retcode : 0
DEBUG 2015-08-05 17:28:16,093: 	 Proxy valid for 23:34:16 hours
INFO 2015-08-05 17:28:16,093: 	 Will use CRAB configuration file crab3_TrackAnalyzer_v1.py
DEBUG 2015-08-05 17:28:16,094: 	 Loading CRAB configuration file.
DEBUG 2015-08-05 17:28:19,737: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-05 17:28:19,738: 	 Working area '/afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects/crab_tutorial_May2015_Data_analysis' already exists 
Please change the requestName in the config file
ERROR 2015-08-05 17:28:19,738: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects/crab_tutorial_May2015_Data_analysis' already exists 
Please change the requestName in the config file
DEBUG 2015-08-05 21:36:14,612: 	 Executing command: 'kill'
DEBUG 2015-08-05 21:36:14,612: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
ERROR 2015-08-05 21:36:14,613: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2015-08-05 21:36:14,613: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 253, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/kill.py", line 51, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 559, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
DEBUG 2015-08-05 21:36:23,180: 	 Executing command: 'kill'
DEBUG 2015-08-05 21:36:23,180: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 21:36:23,208: 	 Checking credentials
DEBUG 2015-08-05 21:36:23,208: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 21:36:23,208: 	 Getting proxy life time left
DEBUG 2015-08-05 21:36:23,926: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -timeleft
 output : 84877

 error: 
 retcode : 0
DEBUG 2015-08-05 21:36:24,437: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -actimeleft
 output : 84876

 error: 
 retcode : 0
DEBUG 2015-08-05 21:36:24,438: 	 Proxy valid for 23:34:37 hours
ERROR 2015-08-05 21:36:24,438: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
ERROR 2015-08-05 21:36:24,438: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 317, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 431, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 439, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
DEBUG 2015-08-05 21:36:34,573: 	 Executing command: 'kill'
DEBUG 2015-08-05 21:36:34,573: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 21:36:34,584: 	 Checking credentials
DEBUG 2015-08-05 21:36:34,584: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 21:36:34,584: 	 Getting proxy life time left
DEBUG 2015-08-05 21:36:35,190: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -timeleft
 output : 84865

 error: 
 retcode : 0
DEBUG 2015-08-05 21:36:35,794: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -actimeleft
 output : 84865

 error: 
 retcode : 0
DEBUG 2015-08-05 21:36:35,794: 	 Proxy valid for 23:34:25 hours
ERROR 2015-08-05 21:36:35,795: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
ERROR 2015-08-05 21:36:35,795: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 317, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 431, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 439, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
DEBUG 2015-08-05 21:36:51,463: 	 Executing command: 'kill'
DEBUG 2015-08-05 21:36:51,464: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 21:36:51,471: 	 Checking credentials
DEBUG 2015-08-05 21:36:51,472: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 21:36:51,472: 	 Getting proxy life time left
DEBUG 2015-08-05 21:36:52,182: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -timeleft
 output : 84848

 error: 
 retcode : 0
DEBUG 2015-08-05 21:36:52,693: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -actimeleft
 output : 84848

 error: 
 retcode : 0
DEBUG 2015-08-05 21:36:52,693: 	 Proxy valid for 23:34:08 hours
ERROR 2015-08-05 21:36:52,693: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
ERROR 2015-08-05 21:36:52,694: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 317, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 431, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 439, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
DEBUG 2015-08-05 21:53:13,214: 	 Executing command: 'status'
DEBUG 2015-08-05 21:53:13,215: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 21:53:13,228: 	 Checking credentials
DEBUG 2015-08-05 21:53:13,229: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 21:53:13,229: 	 Getting proxy life time left
DEBUG 2015-08-05 21:53:13,833: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -timeleft
 output : 83867

 error: 
 retcode : 0
DEBUG 2015-08-05 21:53:14,238: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -actimeleft
 output : 83866

 error: 
 retcode : 0
DEBUG 2015-08-05 21:53:14,239: 	 Proxy valid for 23:17:47 hours
ERROR 2015-08-05 21:53:14,239: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects/crab_tutorial_May2015_Data_analysis
ERROR 2015-08-05 21:53:14,239: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 317, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 431, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 439, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects/crab_tutorial_May2015_Data_analysis
DEBUG 2015-08-05 21:53:43,479: 	 Executing command: 'kill'
DEBUG 2015-08-05 21:53:43,479: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
ERROR 2015-08-05 21:53:43,480: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2015-08-05 21:53:43,480: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 253, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/kill.py", line 51, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 559, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
DEBUG 2015-08-05 21:53:54,383: 	 Executing command: 'kill'
DEBUG 2015-08-05 21:53:54,384: 	 Found CRAB cache file /afs/cern.ch/user/r/rjanjam/.crab3
DEBUG 2015-08-05 21:53:54,391: 	 Checking credentials
DEBUG 2015-08-05 21:53:54,391: 	 Found proxy file /tmp/x509up_u45634
DEBUG 2015-08-05 21:53:54,391: 	 Getting proxy life time left
DEBUG 2015-08-05 21:53:54,898: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -timeleft
 output : 83826

 error: 
 retcode : 0
DEBUG 2015-08-05 21:53:55,412: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u45634 -actimeleft
 output : 83825

 error: 
 retcode : 0
DEBUG 2015-08-05 21:53:55,412: 	 Proxy valid for 23:17:06 hours
ERROR 2015-08-05 21:53:55,413: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
ERROR 2015-08-05 21:53:55,413: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 317, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 431, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 439, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/r/rjanjam/CMSSW_7_4_0_pre6/src/TrackAnalyzer/TrackAnalyzer/python/crab_projects
